In [2]:
import numpy as np
import cv2
import matplotlib.pyplot as plt

In [2]:
kernel1 = np.array([[0.43719608, 0.70202315, 0.4444901],

                    [0.46958 , 0.08807961, 0.83101636],

                    [0.96853405, 0.4169272 , 0.5999559]])


In [3]:
kernel1.shape

(3, 3)

In [16]:
kernel2 = np.array([[0.42089933],
  [0.30614805],
  [0.48108655],

 [0.44783658],
  [0.33110785],
  [0.7673952 ],

 [0.51875657],
  [0.8824891 ],
  [0.7823843 ]])


True

In [3]:
img_path = "Data1/Test/Benign/0 (1).png"
img= cv2.imread(img_path,0)
img = cv2.resize(img,(224,224))
print(img)


[[153 172 186 ... 180 191 186]
 [175 189 196 ... 177 194 188]
 [168 169 170 ... 169 187 186]
 ...
 [157 176 164 ... 171 157 172]
 [137 142 131 ... 177 147 170]
 [174 137 117 ... 172 140 164]]


In [5]:
img = img/ 255
print(img)
cv2.imwrite("resul.png",img)

[[0.00235294 0.00264514 0.00286044 ... 0.00276817 0.00293733 0.00286044]
 [0.00269127 0.00290657 0.00301423 ... 0.00272203 0.00298347 0.0028912 ]
 [0.00258362 0.002599   0.00261438 ... 0.002599   0.00287582 0.00286044]
 ...
 [0.00241446 0.00270665 0.00252211 ... 0.00262976 0.00241446 0.00264514]
 [0.00210688 0.00218378 0.00201461 ... 0.00272203 0.00226067 0.00261438]
 [0.00267589 0.00210688 0.00179931 ... 0.00264514 0.00215302 0.00252211]]


True

In [13]:
x = cv2.filter2D(src=img, ddepth=-1, kernel=kernel2,)
print(x)

[[3.40838189 3.51779107 3.51230799 ... 3.62573402 3.59008155 3.55090229]
 [3.39763696 3.50268532 3.51028718 ... 3.63027969 3.64374069 3.57856179]
 [3.37738401 3.49076769 3.51101591 ... 3.58295172 3.6690985  3.57928718]
 ...
 [3.33540365 3.27713095 3.15356353 ... 3.21341396 2.82448527 3.1496586 ]
 [3.4400234  3.32947915 3.19913972 ... 3.22321492 2.87989544 3.20386506]
 [3.50238058 3.31741495 3.26747265 ... 3.20983283 2.85279589 3.20246373]]


In [14]:
x = x -  x.mean()
x /= x.std ()
x *=  64
x += 128
x  = np.clip(x, 0, 255)

In [15]:
cv2.imwrite("result.png",x)

True